### ISSUE TITLE
8x8 Random Blocks

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#122]
NTSC:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/randomntsc_zpsxlkngjbq.gif)

PAL:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/randompal_zpskwy8p2ob.gif)

They just seem to scroll into view, but it is very intermittent.

Tested on the release build in gens.

**Comment by andwn** [comment]
This is because I pushed the row rendering up to "-15". The upper corners sometimes "miss". I previously fixed it by moving it down to "-14" but I think you can imagine why it's up again.

I'll play with the column scrolling values.

**Comment by andwn** [comment]
Shifted the rendering columns up 8 pixels. Hopefully that fixes it. I tried running up towards the throne room and booster/machine gunning to the upper left and right.

I ran through first cave and didn't see anything bad happen in the lower corners but it's possible it may happen elsewhere. Will look out for it.

**Comment by andwhyisit** [comment]
Since I can no longer reproduce this issue I think I can assume this to be fixed until something proves me wrong.

**Comment by andwhyisit** [comment]
Nope, scratch that. Turns out that the issue is still in effect.

**Comment by andwn** [comment]
which corner?

**Comment by Leo40Git** [comment]
![image](https://cloud.githubusercontent.com/assets/7997354/23341157/f2fe06e2-fc4a-11e6-950b-6364e5ad4e42.png)
The top left corner.

**Comment by andwhyisit** [comment]
Haven't noticed this issue in a while. Marking as fixed.

**Comment by andwhyisit** [comment]
Why is it that these things only appear just after I close the issue?

I saw three of these in the Plantation.

**Comment by andwn** [comment]
Was this right after entering a room and moving to the left a bit? I just noticed the initial screen drawing routine was 1 block to the right of where it should be.

**Comment by andwhyisit** [comment]
I can't ever reproduce it consistently, however it was on the main plantation map in all instances, not in a room. Also I was using the machine gun to boost around at the time, in case this is related to the Jail No.2 issue. They always seem to originate just offscreen as well, but when and where they do is random.

I feel for you on this one. Intermittent issues are a pita.

**Comment by andwn** [comment]
I think the issue was when you are going up/left then switch to down/left because of some unnecessary thing I did. Messed around in Plantation for a while after this change and didn't see it happen.

**Comment by andwhyisit** [comment]
I'll mark this as complete until I see evidence to the contrary.
